### ISSUE TITLE
sage docs: show examples of alternative bud config formats

### ISSUE THREAD

**Issue by retlehs** [roots/docs#399]
in the sage docs, explain that the bud config can also be done in js, yml, json, ts

`.js`
```js
module.exports = async ({env, path, ...app}) =>
  app
    .entry({
      app: ['@scripts/app', '@styles/app'],
      editor: ['@scripts/editor', '@styles/editor'],
    })
    .assets({
      from: path('@src/images'),
      to: path('@public/images'),
    })
    .watch(
      path('@views/**/*'),
      path('app/**/*')
    )
    .serve({
      cert: env.get('BUD_SSL_CERT'),
      key: env.get('BUD_SSL_KEY'),
    })
```

* * *

`.yml`
```yml
entry:
  app:
    - '@scripts/app'
    - '@styles/app'
  editor:
    - '@scripts/editor'
    - '@styles/editor'
assets:
  - images
watch:
  - resources/views/**/*
  - app/**/*
proxy: http://0.0.0.0:8000
serve: http://localhost:3000
```

* * *

`.json`
```json
{
  "entry": {
    "app": ["@scripts/app", "@styles/app"],
    "editor": ["@scripts/editor", "@styles/editor"]
  },
  "assets": ["images"]
}
```

* * *

`.ts`
```ts
export default async ({env, path, ...app}: Framework) =>
  app
    .entry({
      app: ['@scripts/app', '@styles/app'],
      editor: ['@scripts/editor', '@styles/editor'],
    })
    .assets({
      from: path('@src/images'),
      to: path('@public/images'),
    })
    .watch(
      path('@views/**/*'),
      path('app/**/*')
    )
    .serve({
      cert: env.get('BUD_SSL_CERT'),
      key: env.get('BUD_SSL_KEY'),
    })
```
