### ISSUE TITLE
💡 Document "provisioning" crons on deploy

### ISSUE THREAD

**Issue by chrillep** [roots/docs#482]
### Summary

One could argue that crons should be part of the deploy. 😄 
How do we accomplish this?
It would really help me if this was part of the trellis docs. 🙏🏼

AC: (feel free to change them) ❤️ 

Docs
* Should contain how cron works or link to it. (it has become apparent to me, that this is forgotten knowledge 😺. Spanning from an ancient time) 
  * cron as in the system
  * cron as in how you apply it
* Should contain examples of how you provision crons
* Should contain examples on how to update "provision" crons on deploy.
* Should contain descriptions on what each value does in the cron config
* Should contain how you test crons
* Should contain links of Best practices on how to add schedule WP Cron events

### Additional context
On most of our servers we dont have root access, so we only use the deploy part of trellis.
This is from what i gather a common practice?

It would be simpler (for us 😄 ) if the cron was part of the deploy.
It would be simpler (for us 😄 ) if the user owning the crons was the deploy user.

### refs
* https://discourse.roots.io/t/can-someone-explain-to-me-how-cron-jobs-work-in-trellis/6863
* https://github.com/roots/setup-trellis-cli/issues/76
* https://roots.io/bedrock/docs/wp-cron/
* https://discourse.roots.io/t/custom-cron-woes/9107
* https://discourse.roots.io/t/serveral-custom-cron-jobs-in-trellis-bedrock-stack/11291
* https://discourse.roots.io/t/custom-cron-woes/9107
* https://discourse.roots.io/t/permissions-when-adding-a-custom-cron-job-on-deploy-permission-denied/9685

**Comment by chrillep** [comment]
working yaml if you want || need the crons to be setup as part of the deploy chain.

`trellis/deploy-hooks/build-before.yml`
```yaml
- name: Setup WP system cron using crontab
  shell: |
    (crontab -l 2>/dev/null || echo '') | grep -v "{{ item.key }} WordPress cron" | crontab -
    (crontab -l; echo "*/{{ item.value.cron_interval | default('5') }} * * * * cd {{ www_root }}/{{ item.value.current_path | default('current') }} && wp cron event run --due-now > /dev/null 2>&1 # {{ item.key }} WordPress cron") | crontab -
  loop: "{{ wordpress_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: not item.value.multisite.enabled

- name: Setup WP Multisite system cron using crontab
  shell: |
    (crontab -l 2>/dev/null || echo '') | grep -v "{{ item.key }} WordPress network cron" | crontab -
    (crontab -l; echo "*/{{ item.value.cron_interval_multisite | default('10') }} * * * * cd {{ www_root }}/{{ item.value.current_path | default('current') }} && (wp site list --field=url | xargs -n1 -I \\% wp --url=\\% cron event run --due-now) > /dev/null 2>&1 # {{ item.key }} WordPress network cron") | crontab -
  loop: "{{ wordpress_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.multisite.enabled
```
