### ISSUE TITLE
multisite - which/what env dictionary to update?

### ISSUE THREAD

**Issue by matgargano** [roots/docs#63]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a suggestion for new documentation
- [x] This is a suggestion for improving the current documentation
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/docs/issues)

Replace any `X` with your information.

---

## Suggestion for new/improved documentation

(delete this section if not applicable)

**What is the URL for the current documentation (if applicable)?**

https://roots.io/trellis/docs/multisite/

**How can the documentation be improved?**

You have this documentation:

```
You'll also need to define the env dictionary for multisite installs with these three settings:

env:
  domain_current_site: example.com
  wp_home: http://example.com
  wp_siteurl: http://example.com/wp
```

where does this get updated? is it `/trellis/group_vars/all/helpers.yml`? should that be updated to:

```
wordpress_env_defaults:
  db_host: localhost
  db_name: "{{ item.key | underscore }}_{{ env }}"
  db_user: "{{ item.key | underscore }}"
  disable_wp_cron: true
  wp_env: "{{ env }}"
  wp_home: "{{ ssl_enabled | ternary('https', 'http') }}://{{ site_hosts_canonical | first }}"
  wp_siteurl: "{{ ssl_enabled | ternary('https', 'http') }}://{{ site_hosts_canonical | first }}/wp"
  domain_current_site: "{{ site_hosts_canonical | first }}"
```

**How will this benefit users?**

Helpful for getting started!

**Is there a related [Discourse](https://discourse.roots.io/) thread (please link them)?**

https://discourse.roots.io/t/multisite-which-what-env-dictionary-to-update/8420
